### ISSUE TITLE
Use messenger with a Cronjob only

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/t3_messenger#23]
https://dev.to/fadymr/use-symfony-messenger-without-supervisor-3cl6

**Comment by fnagel** [comment]
This might be helpful too: https://github.com/symfony/symfony/pull/43689

**Comment by sabbelasichon** [comment]
So, the link above https://dev.to/fadymr/use-symfony-messenger-without-supervisor-3cl6 does work in the end?

**Comment by fnagel** [comment]
Not quite sure yet. But in a few weeks I should be able to provide some feedback!

**Comment by sabbelasichon** [comment]
Happy to hear your feedback.

**Comment by sabbelasichon** [comment]
This will not be part of the package. If someone wants to use it he/she must add this EventSubscriber and try it out.

**Comment by fnagel** [comment]
@sabbelasichon What EventSubscriber? Can you elaborate please?

**Comment by sabbelasichon** [comment]
@fnagel Sure. I thought this one is helpful here: https://dev.to/fadymr/use-symfony-messenger-without-supervisor-3cl6

**Comment by fnagel** [comment]
Ahh ok. I'm not sure this event is really needed. I think using some thoughtful params should be sufficient, something like: `php bin/console messenger:consume async --limit=1 --time-limit=900` 

Anyway, I think your extension will not be as useful as it could be if using it with cronjob and / or TYPO3 scheduler only is not possible.

**Comment by sabbelasichon** [comment]
Sure. But it should work out of the box then.
