### ISSUE TITLE
RFC: Improve command "t3_messenger:failed-messages-retry"

### ISSUE THREAD

**Issue by nostadt** [sabbelasichon/t3_messenger#54]
Currently the command `t3_messenger:failed-messages-retry` allows to either retry a failed job by using `yes` or deleting the job by using `no`. If you have like 1 or 2 failed jobs it's all good. However, if you have 15 failed jobs and for different reasons and you want to retry the 7th failed job, you have to retry the 6 jobs before as well.

I can imagine following options instead:

- `delete`
- `next`
- `retry`

These are explicit and disregard the need to retry the 6th job before.

**Comment by sabbelasichon** [comment]
Please have a look at https://symfony.com/doc/current/messenger.html#saving-retrying-failed-messages. I think it is already covered. The extension is using the command from the Messenger component under the hood.
